/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import database.medikacomDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY PC
 */
public class MainViewMapel extends javax.swing.JFrame {

    /**
     * Creates new form MainViewMapel
     */
    public MainViewMapel() {
        initComponents();
        tampil_combo();
        datatable();
    }

    public void tampil_combo() {
        try {
            Connection con = medikacomDatabase.getConnection();
            Statement stt = con.createStatement();
            String sql = "select idpengajar from data_pengajar order by idpengajar asc";
            ResultSet res = stt.executeQuery(sql);

            while (res.next()) {
                Object[] ob = new Object[3];
                ob[0] = res.getString(1);

                cbIdPengajar.addItem((String) ob[0]);
            }
            res.close();
            stt.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode mapel");
        tbl.addColumn("ID pengajar");
        tbl.addColumn("Mapel");
        tbl.addColumn("Prog. Keahlian");
        tbl.addColumn("Kurikulum");
        tblMapel.setModel(tbl);
        try {
            Statement statement = (Statement) medikacomDatabase.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select*from data_mapel");
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kodemapel"),
                    res.getString("idpengajar"),
                    res.getString("mapel"),
                    res.getString("pkeahlian"),
                    res.getString("kurikulum")
                });
                tblMapel.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "salah");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataMapel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMapel = new javax.swing.JTable();
        txtKodeMapel = new javax.swing.JTextField();
        txtMapel = new javax.swing.JTextField();
        txtJurusan = new javax.swing.JTextField();
        txtKurikulum = new javax.swing.JTextField();
        buttonAdd = new javax.swing.JButton();
        cbIdPengajar = new javax.swing.JComboBox<>();
        btnLihat = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        buttonEdit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DataMapel.setBackground(new java.awt.Color(0, 153, 0));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 0));
        jLabel18.setText("PENGOLAHAN DATA MATA PELAJARAN");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 0));
        jLabel19.setText("Kode Mata Pelajaran");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 0));
        jLabel20.setText("ID Pengajar");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 0));
        jLabel21.setText("Mata Pelajaran");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 0));
        jLabel22.setText("Prog. Keahlian");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 0));
        jLabel23.setText("Kurikulum ");

        tblMapel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMapelMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblMapel);

        txtKodeMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeMapelActionPerformed(evt);
            }
        });

        txtJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJurusanActionPerformed(evt);
            }
        });

        buttonAdd.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        buttonAdd.setText("Tambah Data");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        cbIdPengajar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih ID Pengajar-" }));
        cbIdPengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdPengajarActionPerformed(evt);
            }
        });

        btnLihat.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnLihat.setText("Lihat Data");
        btnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatActionPerformed(evt);
            }
        });

        buttonDelete.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        buttonDelete.setText("Hapus Data");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonReset.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        buttonReset.setText("Reset Data");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        buttonEdit1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        buttonEdit1.setText("Ubah Data");
        buttonEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEdit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataMapelLayout = new javax.swing.GroupLayout(DataMapel);
        DataMapel.setLayout(DataMapelLayout);
        DataMapelLayout.setHorizontalGroup(
            DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataMapelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataMapelLayout.createSequentialGroup()
                        .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DataMapelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKodeMapel))
                            .addGroup(DataMapelLayout.createSequentialGroup()
                                .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23))
                                .addGap(44, 44, 44)
                                .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJurusan)
                                    .addComponent(txtMapel)
                                    .addComponent(txtKurikulum)
                                    .addComponent(cbIdPengajar, 0, 253, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataMapelLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(304, 304, 304)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DataMapelLayout.createSequentialGroup()
                        .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(DataMapelLayout.createSequentialGroup()
                                    .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel18)))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        DataMapelLayout.setVerticalGroup(
            DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataMapelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(11, 11, 11)
                .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtKodeMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbIdPengajar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DataMapelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(3, 3, 3))
                    .addComponent(txtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtKurikulum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(btnLihat)
                    .addComponent(buttonDelete)
                    .addComponent(buttonReset)
                    .addComponent(btnBack)
                    .addComponent(buttonEdit1))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(DataMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(DataMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMapelActionPerformed

    private void txtJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJurusanActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        String kodemapel = txtKodeMapel.getText();
        Integer idpengajar = Integer.parseInt(cbIdPengajar.getSelectedItem().toString());
        String mapel = txtMapel.getText();
        String pkeahlian = txtJurusan.getText();
        String kurikulum = txtKurikulum.getText();
        try {
            Statement statement = (Statement) medikacomDatabase.getConnection().createStatement();
            statement.executeUpdate("insert into data_mapel values ('" + kodemapel + "','" + idpengajar + "','" + mapel + "','" + pkeahlian + "','" + kurikulum + "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        } catch (Throwable throwable) {
            JOptionPane.showMessageDialog(null, new Object[]{
                "Terjadi error di database dengan pesan ", throwable.getMessage()});
        }

    }//GEN-LAST:event_buttonAddActionPerformed

    private void cbIdPengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdPengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdPengajarActionPerformed

    private void btnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatActionPerformed
        // TODO add your handling code here:
        try {
            Object[] rows = {"Kode mapel", "ID pengajar", "Mapel", "Prog. Keahlian", "Kurikulum"};
            DefaultTableModel dtm = new DefaultTableModel(null, rows);
            tblMapel.setModel(dtm);
            tblMapel.setBorder(null);
            jScrollPane4.setVisible(true);
            jScrollPane4.setViewportView(tblMapel);
            String kodemapel = "", idpengajar = "", mapel = "", pkeahlian = "", kurikulum = "";
            try {
                String sql = "select * from data_mapel";
                Connection conn = medikacomDatabase.getConnection();
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    kodemapel = rs.getString("kodemapel");
                    idpengajar = rs.getString("idpengajar");
                    mapel = rs.getString("mapel");
                    pkeahlian = rs.getString("pkeahlian");
                    kurikulum = rs.getString("kurikulum");

                    String[] tampil = {"" + kodemapel, idpengajar, mapel, pkeahlian, kurikulum};
                    dtm.addRow(tampil);
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Query Salah " + e);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLihatActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan menghapus data ini?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                String sql = "delete from data_mapel where kodemapel='" + txtKodeMapel.getText() + "'";
                Connection conn = medikacomDatabase.getConnection();
                PreparedStatement st = conn.prepareStatement(sql);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Hapus data sukses!");
            } catch (Throwable throwable) {
                JOptionPane.showMessageDialog(null, new Object[]{
                    "Terjadi error di database dengan pesan ", throwable.getMessage()});
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        txtKodeMapel.setText("");
        txtMapel.setText("");
        txtJurusan.setText("");
        txtKurikulum.setText("");
    }//GEN-LAST:event_buttonResetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        HomeView HV = new HomeView();
        HV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void buttonEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEdit1ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan mengupdate data ini?", "Confirmation", JOptionPane.YES_NO_OPTION);
        try {
            String sql = "update data_mapel set kodemapel=?, idpengajar=?, mapel=?, pkeahlian=?, kurikulum=? where kodemapel='" + txtKodeMapel.getText() + "'";
            Connection conn = medikacomDatabase.getConnection();
            PreparedStatement st = conn.prepareStatement(sql);
            if (ok == 0) {
                try {
                    st.setString(1, txtKodeMapel.getText());
                    st.setString(2, cbIdPengajar.getSelectedItem().toString());
                    st.setString(3, txtMapel.getText());
                    st.setString(4, txtJurusan.getText());
                    st.setString(5, txtKurikulum.getText());
                    st.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Update data sukses!");
                } catch (Throwable throwable) {
                    JOptionPane.showMessageDialog(null, new Object[]{
                        "Terjadi error di database dengan pesan ", throwable.getMessage()});
                }
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_buttonEdit1ActionPerformed

    private void tblMapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMapelMouseClicked
        // TODO add your handling code here:
        txtKodeMapel.setText(tblMapel.getValueAt(tblMapel.getSelectedRow(), 0).toString());
        cbIdPengajar.setSelectedItem(tblMapel.getValueAt(tblMapel.getSelectedRow(), 1).toString());
        txtMapel.setText(tblMapel.getValueAt(tblMapel.getSelectedRow(), 2).toString());
        txtJurusan.setText(tblMapel.getValueAt(tblMapel.getSelectedRow(), 3).toString());
        txtKurikulum.setText(tblMapel.getValueAt(tblMapel.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tblMapelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainViewMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainViewMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainViewMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainViewMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainViewMapel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataMapel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLihat;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit1;
    private javax.swing.JButton buttonReset;
    private javax.swing.JComboBox<String> cbIdPengajar;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblMapel;
    private javax.swing.JTextField txtJurusan;
    private javax.swing.JTextField txtKodeMapel;
    private javax.swing.JTextField txtKurikulum;
    private javax.swing.JTextField txtMapel;
    // End of variables declaration//GEN-END:variables
}
