/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import database.medikacomDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY PC
 */
public class MainViewSiswa extends javax.swing.JFrame {

    /**
     * Creates new form MainViewSiswa
     */
    public MainViewSiswa() {
        initComponents();
        datatable();
    }

    public void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NIS");
        tbl.addColumn("Nama");
        tbl.addColumn("Kelas");
        tbl.addColumn("Jk");
        tbl.addColumn("Ttl");
        tbl.addColumn("Alamat");
        tbl.addColumn("No. Hp");
        tblSiswa.setModel(tbl);
        try {
            Statement statement = (Statement) medikacomDatabase.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select*from data_siswa");
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("nis"),
                    res.getString("nama"),
                    res.getString("kelas"),
                    res.getString("jk"),
                    res.getString("ttl"),
                    res.getString("alamat"),
                    res.getString("nohp")
                });
                tblSiswa.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "salah");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataSiswa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNisSiswa = new javax.swing.JTextField();
        txtNamaSiswa = new javax.swing.JTextField();
        txtKelasSiswa = new javax.swing.JTextField();
        txtTtlSiswa = new javax.swing.JTextField();
        txtAlamatSiswa = new javax.swing.JTextField();
        txtNoTelpSiswa = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSiswa = new javax.swing.JTable();
        btnLihat = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnResetData = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        cbJK = new javax.swing.JComboBox<>();
        btnEdit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DataSiswa.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("PENGOLAHAN DATA SISWA");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("No Induk Siswa");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Nama ");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Kelas");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Jenis Kelamin ");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Tempat, tanggal lahir");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("Alamat");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("No. Telp");

        txtNisSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNisSiswaActionPerformed(evt);
            }
        });

        txtKelasSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelasSiswaActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnAdd.setText("Tambah Data");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSiswa);

        btnLihat.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnLihat.setText("Lihat Data");
        btnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnDelete.setText("Hapus Data");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnResetData.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnResetData.setText("Reset Data");
        btnResetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDataActionPerformed(evt);
            }
        });

        btnBack1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnBack1.setText("Kembali");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        cbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Jenis Kelamin -", "Laki-laki", "Perempuan", " " }));

        btnEdit1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnEdit1.setText("Ubah Data");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataSiswaLayout = new javax.swing.GroupLayout(DataSiswa);
        DataSiswa.setLayout(DataSiswaLayout);
        DataSiswaLayout.setHorizontalGroup(
            DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataSiswaLayout.createSequentialGroup()
                        .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAlamatSiswa)
                            .addComponent(txtNisSiswa)
                            .addComponent(txtNamaSiswa)
                            .addComponent(txtKelasSiswa)
                            .addComponent(txtTtlSiswa)
                            .addComponent(txtNoTelpSiswa)
                            .addComponent(cbJK, 0, 254, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DataSiswaLayout.createSequentialGroup()
                        .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(DataSiswaLayout.createSequentialGroup()
                                    .addComponent(btnAdd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnResetData, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 17, Short.MAX_VALUE))))
        );
        DataSiswaLayout.setVerticalGroup(
            DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNisSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKelasSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTtlSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAlamatSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNoTelpSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLihat)
                        .addComponent(btnDelete)
                        .addComponent(btnResetData)
                        .addComponent(btnBack1))
                    .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnEdit1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(DataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(DataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNisSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNisSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNisSiswaActionPerformed

    private void txtKelasSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasSiswaActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Integer nis = Integer.parseInt(txtNisSiswa.getText());
        String nama = txtNamaSiswa.getText();
        String kelas = txtKelasSiswa.getText();
        String jk = cbJK.getSelectedItem().toString();
        String ttl = txtTtlSiswa.getText();
        String alamat = txtAlamatSiswa.getText();
        Integer nohp = Integer.parseInt(txtNoTelpSiswa.getText());
        try {
            Statement statement = (Statement) medikacomDatabase.getConnection().createStatement();
            statement.executeUpdate("insert into data_siswa values ('" + nis + "','" + nama + "','" + kelas + "','" + jk + "','" + ttl + "','" + alamat + "','" + nohp + "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        } catch (Throwable throwable) {
            JOptionPane.showMessageDialog(null, new Object[]{
                "Terjadi error di database dengan pesan ", throwable.getMessage()});
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatActionPerformed
        // TODO add your handling code here:
        try {
            Object[] rows = {"NIS", "Nama", "Kelas", "JK", "Ttl", "Alamat", "No. Hp"};
            DefaultTableModel dtm = new DefaultTableModel(null, rows);
            tblSiswa.setModel(dtm);
            tblSiswa.setBorder(null);
            jScrollPane1.setVisible(true);
            jScrollPane1.setViewportView(tblSiswa);
            int nis = 1;
            String nama = "", kelas = "", jk = "", ttl = "", alamat = "", nohp = "";
            try {
                String sql = "select * from data_siswa";
                Connection conn = medikacomDatabase.getConnection();
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    nis = rs.getInt("nis");
                    nama = rs.getString("nama");
                    kelas = rs.getString("kelas");
                    jk = rs.getString("jk");
                    ttl = rs.getString("ttl");
                    alamat = rs.getString("alamat");
                    nohp = rs.getString("nohp");

                    String[] tampil = {"" + nis++, nama, kelas, jk, ttl, alamat, nohp};
                    dtm.addRow(tampil);
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Query Salah " + e);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLihatActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan menghapus data ini?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                String sql = "delete from data_siswa where nis='" + txtNisSiswa.getText() + "'";
                Connection conn = medikacomDatabase.getConnection();
                PreparedStatement st = conn.prepareStatement(sql);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Hapus data sukses!");
            } catch (Throwable throwable) {
                JOptionPane.showMessageDialog(null, new Object[]{
                    "Terjadi error di database dengan pesan ", throwable.getMessage()});
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDataActionPerformed
        // TODO add your handling code here:
        txtNisSiswa.setText("");
        txtNamaSiswa.setText("");
        txtKelasSiswa.setText("");
        txtTtlSiswa.setText("");
        txtAlamatSiswa.setText("");
        txtNoTelpSiswa.setText("");
    }//GEN-LAST:event_btnResetDataActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        HomeView HV = new HomeView();
        HV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan mengupdate data ini?", "Confirmation", JOptionPane.YES_NO_OPTION);
        try {
            String sql = "update data_siswa set nis=?, nama=?, kelas=?, jk=?, ttl=?, alamat=?, nohp=? where nis='" + txtNisSiswa.getText() + "'";
            Connection conn = medikacomDatabase.getConnection();
            PreparedStatement st = conn.prepareStatement(sql);
            if (ok == 0) {
                try {
                    st.setString(1, txtNisSiswa.getText());
                    st.setString(2, txtNamaSiswa.getText());
                    st.setString(3, txtKelasSiswa.getText());
                    st.setString(4, cbJK.getSelectedItem().toString());
                    st.setString(5, txtTtlSiswa.getText());
                    st.setString(6, txtAlamatSiswa.getText());
                    st.setString(7, txtNoTelpSiswa.getText());

                    st.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Update data sukses!");
                } catch (Throwable throwable) {
                    JOptionPane.showMessageDialog(null, new Object[]{
                        "Terjadi error di database dengan pesan ", throwable.getMessage()});
                }
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void tblSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSiswaMouseClicked
        // TODO add your handling code here:
        txtNisSiswa.setText(tblSiswa.getValueAt(tblSiswa.getSelectedRow(), 0).toString());
        txtNamaSiswa.setText(tblSiswa.getValueAt(tblSiswa.getSelectedRow(), 1).toString());
        txtKelasSiswa.setText(tblSiswa.getValueAt(tblSiswa.getSelectedRow(), 2).toString());        
        txtTtlSiswa.setText(tblSiswa.getValueAt(tblSiswa.getSelectedRow(), 4).toString());
        txtAlamatSiswa.setText(tblSiswa.getValueAt(tblSiswa.getSelectedRow(), 5).toString());
        txtNoTelpSiswa.setText(tblSiswa.getValueAt(tblSiswa.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_tblSiswaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainViewSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainViewSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainViewSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainViewSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainViewSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataSiswa;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnLihat;
    private javax.swing.JButton btnResetData;
    private javax.swing.JComboBox<String> cbJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSiswa;
    private javax.swing.JTextField txtAlamatSiswa;
    private javax.swing.JTextField txtKelasSiswa;
    private javax.swing.JTextField txtNamaSiswa;
    private javax.swing.JTextField txtNisSiswa;
    private javax.swing.JTextField txtNoTelpSiswa;
    private javax.swing.JTextField txtTtlSiswa;
    // End of variables declaration//GEN-END:variables
}
